### PR TITLE
Export PRAS SystemModel as a .pras file

### PR DESCRIPTION
**Pull request by scdhulipala**
This PR containes module which takes the SystemModel and .pras file location as arguments and export the SystemModel as a .pras file.

### CODE REVIEW

**Comment by GordStephen** [comment]
I'd like to get this merged before v0.6. Do you have any tests for this? I've been making some changes on another branch: https://github.com/NREL/PRAS/tree/dsc/save-systemmodel

**Comment by GordStephen** [comment]
@scdhulipala I think I'm good to merge https://github.com/NREL/PRAS/tree/dsc/save-systemmodel - if you're happy with how things look there, I'll apply those changes to this branch and merge this PR

**Comment by scdhulipala** [comment]
@GordStephen  Looks good to me. Thanks for including tests.

**Comment by GordStephen** [comment]
Great! I rebased as well to clean up the commit history. Thanks again!

**Pull request merged**
